language: ruby
cache: bundler
env:
  matrix:
  - DEPLOY_ENVIRONMENT=staging DEPLOY_BRANCH=master
  - DEPLOY_ENVIRONMENT=production DEPLOY_TAGS=true
  - ""

rvm:
  - 2.3.1

services:
  - docker

addons:
  apt:
    packages:
    - libpq-dev
    - libmagickcore-dev
    - libmagickwand-dev
install:
  - if [ -z "${DEPLOY_ENVIRONMENT}" ]; then gem install bundler; fi
  - if [ -z "${DEPLOY_ENVIRONMENT}" ]; then bundle install; fi
script:
  - if [ -z "${DEPLOY_ENVIRONMENT}" ]; then docker build . -t dreams; fi
  - if [ -z "${DEPLOY_ENVIRONMENT}" ]; then bundle exec rspec spec -fd; fi
  - .travis/continuous_deployment.sh
notifications:
  email: false

